// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mobo_manufacturing_app/MO/pages/MoList/service/hive/models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveBomAdapter());
    registerAdapter(HiveProductAdapter());
    registerAdapter(HiveUserModelAdapter());
    registerAdapter(HiveWorkCenterAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HiveBomAdapter());
    registerAdapter(HiveProductAdapter());
    registerAdapter(HiveUserModelAdapter());
    registerAdapter(HiveWorkCenterAdapter());
  }
}
