import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/services.dart' show rootBundle, Uint8List;
import 'package:flutter/rendering.dart';
import '../../../../shared/widgets/snackbar.dart';
import '../models/mo_work_order.dart';
import '../models/stock_move.dart';
import 'mo_form_service.dart';

/// Utility class responsible for generating and saving a PDF overview document
/// for a Manufacturing Order (MO).
///
/// The generated PDF includes:
/// • Header with MO name, product, quantity, status, expected receipt date
/// • Materials table (components/stock moves) with costs
/// • Work orders table with operation names, statuses, durations, and costs
/// • Total estimated MO cost, real cost, and operation hours
///
/// Uses `pdf` package to build the document and `file_picker` to let user choose save location.
/// Loads custom fonts (Manrope Regular & Bold) from assets.
/// Shows success/error snackbars via `CustomSnackbar`.
class PdfGenerator {
  final List<dynamic> moItem;
  final List<StockMove> moveProducts;
  final List<MoWorkOrder> workOrders;
  final BuildContext context;

  PdfGenerator({
    required this.moItem,
    required this.workOrders,
    required this.moveProducts,
    required this.context,
  });

  /// Returns display text and color for Manufacturing Order (MRP) state
  StateInfo getMoStateInfo(String? state) {
    switch ((state ?? '').toLowerCase()) {
      case 'draft':
        return StateInfo('Draft', Colors.blue);
      case 'confirmed':
        return StateInfo('Confirmed', Colors.teal);
      case 'progress':
        return StateInfo('In Progress', Colors.orange);
      case 'to_close':
        return StateInfo('To Close', Colors.green);
      case 'done':
        return StateInfo('Done', Colors.green.shade900);
      case 'cancel':
        return StateInfo('Cancelled', Colors.redAccent);
      default:
        return StateInfo(state?.toUpperCase() ?? 'UNKNOWN', Colors.grey);
    }
  }

  /// Builds a status chip widget for MO state (used only in UI preview if needed)
  Widget buildMoStatusChip(String? state) {
    final moInfo = getMoStateInfo(state);

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: moInfo.color,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Text(
        moInfo.text,
        style: const TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }

  /// Returns display text and color for work order (operation) status
  StateInfo getOperationStatusInfo(String? status) {
    switch ((status ?? '').toLowerCase()) {
      case 'pending':
        return StateInfo('Waiting for another WO', Colors.teal);
      case 'waiting':
        return StateInfo('Waiting for Components', Colors.amber);
      case 'ready':
        return StateInfo('Ready', Colors.blue);
      case 'progress':
        return StateInfo('In Progress', Colors.orange);
      case 'done':
        return StateInfo('Finished', Colors.green);
      case 'cancel':
        return StateInfo('Cancelled', Colors.redAccent);
      default:
        return StateInfo((status ?? 'UNKNOWN').toUpperCase(), Colors.grey);
    }
  }

  /// Builds a status chip widget for work order state (used only in UI preview if needed)
  Widget buildOperationStatusChip(String? status) {
    final info = getOperationStatusInfo(status);

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: info.color,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Text(
        info.text,
        style: const TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }

  /// Main method: generates the full PDF document and prompts user to save it.
  ///
  /// Steps:
  /// 1. Loads custom fonts from assets (Manrope Regular & Bold)
  /// 2. Fetches unit costs for each component from Odoo
  /// 3. Calculates total MO cost (availability-aware) and real cost
  /// 4. Calculates total operation hours from work orders
  /// 5. Builds PDF structure with header, materials table, work orders table
  /// 6. Saves generated bytes via file picker
  /// 7. Shows success/error snackbar
  Future<void> generateAndSavePdf() async {
    try {
      final pdf = pw.Document();

      // Load custom fonts from assets
      final regularFont = pw.Font.ttf(
        await rootBundle.load('fonts/Manrope-Regular.ttf'),
      );
      final boldFont = pw.Font.ttf(
        await rootBundle.load('fonts/Manrope-Bold.ttf'),
      );

      final baseTextStyle = pw.TextStyle(font: regularFont, fontSize: 12);
      final boldTextStyle = pw.TextStyle(font: boldFont, fontSize: 12);

      // Extract basic MO info
      final moName = moItem[0]['name'] ?? 'Unnamed MO';
      final moProduct = moItem[0]['product_id']?[1] ?? 'Unnamed Product';
      final moQty = moItem[0]['product_qty'] ?? 0.0;
      final moState = moItem[0]['state'] ?? 'unknown';
      final moInfo = getMoStateInfo(moState);

      final moFinishedDate = moItem[0]['date_finished'] != null
          ? moItem[0]['date_finished'].toString().split(' ')[0]
          : '-';

      // ─── Calculate material costs ───────────────────────────────────────
      double totalMoCost = 0;
      double totalRealCost = 0;

      final odooMoService = MoFormService();
      await odooMoService.initializeClient();
      List<Map<String, dynamic>> materialsData = [];

      for (var product in moveProducts) {
        List<dynamic> productDetails = await odooMoService.loadProductDetails(
          product.productId?[0],
        );

        double unitCost = productDetails[0]['standard_price'] ?? 0.0;
        double moCost =
            (product.availability != null && product.availability! > 0)
            ? product.availability! * unitCost
            : unitCost * (product.toConsume ?? 0.0);
        double realCost = unitCost * (product.toConsume ?? 0.0);

        totalMoCost += moCost;
        totalRealCost += realCost;

        materialsData.add({
          'description': product.productId?[1] ?? 'Unnamed Product',
          'quantity': product.toConsume ?? 0.0,
          'unitCost': unitCost,
          'moCost': moCost,
          'realCost': realCost,
        });
      }

      double totalOperationHours = 0;

      // ─── Build PDF content ──────────────────────────────────────────────
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          build: (context) => [
            // Header title
            pw.Header(
              level: 0,
              child: pw.Text(
                'Manufacturing Order Overview',
                style: pw.TextStyle(font: boldFont, fontSize: 20),
              ),
            ),

            pw.SizedBox(height: 10),

            // Basic MO info
            pw.Text("MO Name: $moName", style: baseTextStyle),
            pw.Text("Product: $moProduct", style: baseTextStyle),
            pw.Text("Quantity: $moQty", style: baseTextStyle),
            pw.Text(
              "Status: ${moInfo.text}",
              style: pw.TextStyle(
                font: boldFont,
                fontSize: 12,
                color: toPdfColor(moInfo.color),
              ),
            ),
            pw.Text("Receipt Date: $moFinishedDate", style: baseTextStyle),

            pw.SizedBox(height: 20),

            // Materials section
            pw.Text(
              'Materials',
              style: pw.TextStyle(font: boldFont, fontSize: 16),
            ),
            pw.SizedBox(height: 8),
            pw.Table.fromTextArray(
              headers: [
                'Description',
                'Quantity',
                'Unit Cost',
                'MO Cost',
                'Real Cost',
              ],
              data: materialsData.map((item) {
                return [
                  item['description'],
                  item['quantity'].toStringAsFixed(2),
                  item['unitCost'].toStringAsFixed(2),
                  item['moCost'].toStringAsFixed(2),
                  item['realCost'].toStringAsFixed(2),
                ];
              }).toList(),
              headerStyle: pw.TextStyle(
                font: boldFont,
                fontSize: 12,
                color: PdfColors.white,
              ),
              headerDecoration: pw.BoxDecoration(color: PdfColors.blue),
              cellStyle: baseTextStyle,
              border: pw.TableBorder.all(color: PdfColors.grey),
              cellAlignment: pw.Alignment.centerLeft,
            ),

            pw.SizedBox(height: 10),
            pw.Text(
              'Total MO Cost: ${totalMoCost.toStringAsFixed(2)}',
              style: boldTextStyle,
            ),
            pw.Text(
              'Total Real Cost: ${totalRealCost.toStringAsFixed(2)}',
              style: boldTextStyle,
            ),

            pw.SizedBox(height: 20),

            // Work Orders section
            pw.Text(
              'Work Orders',
              style: pw.TextStyle(font: boldFont, fontSize: 16),
            ),
            pw.SizedBox(height: 8),

            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey),
              columnWidths: {
                0: const pw.FlexColumnWidth(3),
                1: const pw.FlexColumnWidth(3),
                2: const pw.FlexColumnWidth(2),
                3: const pw.FlexColumnWidth(2),
              },
              children: [
                // Table header

                pw.TableRow(
                  decoration: pw.BoxDecoration(color: PdfColors.deepPurple),
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        'Operation',
                        style: pw.TextStyle(
                          font: boldFont,
                          fontSize: 12,
                          color: PdfColors.white,
                        ),
                      ),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        'Status',
                        style: pw.TextStyle(
                          font: boldFont,
                          fontSize: 12,
                          color: PdfColors.white,
                        ),
                      ),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        'Duration (hh:mm)',
                        style: pw.TextStyle(
                          font: boldFont,
                          fontSize: 12,
                          color: PdfColors.white,
                        ),
                      ),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        'Cost/Hour',
                        style: pw.TextStyle(
                          font: boldFont,
                          fontSize: 12,
                          color: PdfColors.white,
                        ),
                      ),
                    ),
                  ],
                ),

                // Work order rows
                ...workOrders.map((operation) {
                  final statusInfo = getOperationStatusInfo(operation.state);

                  return pw.TableRow(
                    children: [
                      pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text(
                          operation.operation ?? 'Unnamed Operation',
                          style: baseTextStyle,
                        ),
                      ),

                      pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text(
                          statusInfo.text,
                          style: pw.TextStyle(
                            font: boldFont,
                            fontSize: 12,
                            color: toPdfColor(statusInfo.color),
                          ),
                        ),
                      ),

                      pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text(
                          operation.formattedDuration ?? '0:00',
                          style: baseTextStyle,
                        ),
                      ),

                      pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text(
                          (operation.costs_hour?.toStringAsFixed(2) ?? '0.00'),
                          style: baseTextStyle,
                        ),
                      ),
                    ],
                  );
                }).toList(),
              ],
            ),

            pw.SizedBox(height: 10),

            pw.Text(
              'Total Operation Hours: ${totalOperationHours.toStringAsFixed(2)}',
              style: boldTextStyle,
            ),
          ],
        ),
      );

      final pdfBytes = await pdf.save();
      await savePdfToUserSelectedLocation(pdfBytes);
    } catch (e) {
      CustomSnackbar.showError(context, "Failed to generate PDF");
    }
  }

  /// Opens file picker and saves PDF bytes to user-selected location.
  ///
  /// Shows success/error snackbar based on result.
  Future<void> savePdfToUserSelectedLocation(Uint8List pdfBytes) async {
    try {
      await FilePicker.platform.saveFile(
        dialogTitle: "Save PDF",
        fileName: "MO_Overview_${DateTime.now().millisecondsSinceEpoch}.pdf",
        bytes: pdfBytes,
        type: FileType.custom,
        allowedExtensions: ['pdf'],
      );

      CustomSnackbar.showSuccess(context, "PDF saved successfully");
    } catch (e) {
      CustomSnackbar.showError(context, "Failed to save PDF");
    }
  }
}

class StateInfo {
  final String text;
  final Color color;

  StateInfo(this.text, this.color);
}

/// Converts Flutter `Color` to `pdf` package `PdfColor`
PdfColor toPdfColor(Color color) {
  return PdfColor.fromInt(color.value);
}
